name: UmBox upload

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y mingw-w64
      - uses: marekmaskarinec/umbox@master
        with:
          secret: ${{ secrets.UMBOX }}